### ISSUE TITLE
fix not empty (!empty)

### ISSUE THREAD

**Issue by oussamaelwarraki** [sahusoftcom/youtube-livestream-api#1]
you check if the value is not empty and you return false and that stopped the process 

https://github.com/sahusoftcom/youtube-livestream-api/blob/e7354b6121d00dda41d1fccef0c1d950838f8c60/src/YoutubeLiveEventService.php#L367

**Comment by faizahmedfarooqui** [comment]
@oussamaelwarraki 

I guess we should stop the process if the token is empty, because everything after that is going to fail anyway.
