### ISSUE TITLE
Private life streaming

### ISSUE THREAD

**Issue by ronlinet** [sahusoftcom/youtube-livestream-api#2]
Does it stream private youtube live videos ?

**Comment by rondip-geekyants** [comment]
@ronlinet, Currently the package only supports public streaming. If you need it let me know, we can make that feature.

**Comment by ronlinet** [comment]
Hi @rondip-geekyants than you for getting back to me. 
Yes this option will be more than welcome. 
Before I test this can you please advise if your package works with 'unlisted' live streaming?
Thank you for your time!

**Comment by alchemyguy** [comment]
@ronlinet private livestreaming is already available in the package, you just need to pass a privacy_status parameter in the data array while [creating event](https://github.com/sahusoftcom/youtube-livestream-api#creating-a-youtube-event)
```php
data['privacy_status']= "private"; 
```

**Comment by ronlinet** [comment]
@alchemyguy Hat off for your excellent job !!
