### ISSUE TITLE
Undefined offset: 0

### ISSUE THREAD

**Issue by jaythegeek** [sahusoftcom/youtube-livestream-api#5]
When creating broadcast.

Keep getting this 9 times out of 10! Cannot find the source of it just yet, great work though got me started with the live api. If I find a proper fix will PR. If you know of one please let me know.
Thanks

**Comment by alchemyguy** [comment]
@jaythegeek  can you share the code you are using to call the broadcast function. Because I just Checked and it works fine for me.

**Comment by anasmahjub1** [comment]
Have you solved the error ?..
 I have the same error ..

**Comment by alchemyguy** [comment]
@anasmahjub1 
did you set 'event_start_date_time' and 'time_zone' in the data array passed in the broadcast event?
if not please add these to the data array.
If you still face this problem please share the code where the error is occurring.

**Comment by anasmahjub1** [comment]
this array of data
    $data = array(
        "title" => "test title",
        "description" => "test description",
        "thumbnail_path" => "",				
        "event_start_date_time" => "2019-01-25 13:34:43",
        "event_end_date_time" => "",			
        "time_zone" => "UTC",
        'privacy_status' => "public",				
        "language_name" => "English",				
        "tag_array" => "tag tag tag"				
    );

**Comment by anasmahjub1** [comment]
broadcasting 
<img width="832" alt="screen shot 2019-01-25 at 2 03 27 am" src="https://user-images.githubusercontent.com/19223351/51716467-8f44e500-2045-11e9-9c48-8ae446e114b9.png">

Undefined offset: 0 in Class YoutubeLiveEventService
<img width="942" alt="screen shot 2019-01-25 at 2 04 05 am" src="https://user-images.githubusercontent.com/19223351/51716485-9e2b9780-2045-11e9-9542-443debcb425a.png">

**Comment by alchemyguy** [comment]
The issue is solved in the updated package now.
