### ISSUE TITLE
Stream is inactive in Starting a Youtube Event Stream

### ISSUE THREAD

**Issue by anasmahjub1** [sahusoftcom/youtube-livestream-api#6]
this error
<img width="1440" alt="screen shot 2019-01-25 at 6 07 16 pm" src="https://user-images.githubusercontent.com/19223351/51759083-163e9f80-20d0-11e9-8aca-c3db7722c33a.png">
this code ..

<img width="786" alt="screen shot 2019-01-25 at 6 37 51 pm" src="https://user-images.githubusercontent.com/19223351/51759232-6ae21a80-20d0-11e9-908c-25260ccadd9d.png">

**Comment by faizahmedfarooqui** [comment]
Please go through the [Youtube Live Streaming API Errors Documentation](https://developers.google.com/youtube/v3/live/docs/errors) to better understand responses from YouTube. 

### liveBroadcasts.transition
| Error Type | Error detail | Description |
| --- | --- | --- |
| forbidden (403) | errorStreamInactive | The requested transition is not allowed when the stream that is bound to the broadcast is inactive. |

Meaning the server-url & server-key combination available for the event din't received any content to enable the stream.

**Comment by anasmahjub1** [comment]
thanks you ..
i dont know where i using the server-url & server-key ?!..
