### ISSUE TITLE
How to use this package?

### ISSUE THREAD

**Issue by caturseptian** [sahusoftcom/youtube-livestream-api#7]
ErrorException thrown with message "Undefined property: sahusoftcom\YoutubeApi\AuthService::$getLoginUrl"
![image](https://user-images.githubusercontent.com/13551379/53540711-376c3300-3b49-11e9-8472-bfb70e7ef0d5.png)

How to use this package?
I dont understand

**Comment by faizahmedfarooqui** [comment]
@caturseptian 

The documentation is incorrect. 

If you can review the AuthService Class, you will find out that [loginUrl](https://github.com/sahusoftcom/youtube-livestream-api/blob/master/src/AuthService.php#L65-#L91) is a method not variable. You need to send in the email address.

**Comment by faizahmedfarooqui** [comment]
@alchemyguy Can we update the [Authentication / Authorization](https://github.com/sahusoftcom/youtube-livestream-api#authentication-and-authorization) section in Readme?

**Comment by caturseptian** [comment]
> @caturseptian
> 
> The documentation is incorrect.
> 
> If you can review the AuthService Class, you will find out that [loginUrl](https://github.com/sahusoftcom/youtube-livestream-api/blob/master/src/AuthService.php#L65-#L91) is a method not variable. You need to send in the email address.

I don't get it, 
can I display a live stream list like [the one in this documentation](https://developers.google.com/youtube/v3/live/docs/liveStreams/list) without repeated authorizations?

**Comment by caturseptian** [comment]
> @alchemyguy Can we update the [Authentication / Authorization](https://github.com/sahusoftcom/youtube-livestream-api#authentication-and-authorization) section in Readme?

Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Class 'sahusoftcom\YoutubeApi\AuthService' not found"

while sahusoftcom change to SahusoftCom 

![image](https://user-images.githubusercontent.com/13551379/53551295-89be4b80-3b6b-11e9-90d5-2ecf5f2b4427.png)

**Comment by alchemyguy** [comment]
@faizahmedfarooqui  @caturseptian  I have updated the Readme for `Auth`.

**Comment by alchemyguy** [comment]
@faizahmedfarooqui @caturseptian  I have fixed the issue in the package, please install v2.0.0 and follow the steps in the documentation.
If you still face issues you can use this package https://github.com/alchemyguy/YoutubeLaravelApi.
It's up to date with the API depreciation issues too.

**Comment by caturseptian** [comment]
> @faizahmedfarooqui @caturseptian I have updated the Readme for `Auth`.

ErrorException thrown with message "Undefined variable: authcode"

`$authServiceObject = new AuthService();
$authToken = $authServiceObject->getToken($authcode);`

**Comment by alchemyguy** [comment]
```php
$authServiceObject = new AuthService(); 
$authToken = $authServiceObject>getToken($authcode);
```
It works fine, read the documentation on where to get `$authcode` from [HERE](https://github.com/sahusoftcom/youtube-livestream-api#authentication-and-authorization)

**Comment by caturseptian** [comment]
> ```
> $authServiceObject = new AuthService(); 
> $authToken = $authServiceObject>getToken($authcode);
> ```
> 
> It works fine, read the documentation on where to get `$authcode` from [HERE](https://github.com/sahusoftcom/youtube-livestream-api#authentication-and-authorization)

sorry, I was wrong ... this time it worked ..

but is there a way to get a live broadcast list without having to do ask permissions and authorization access step?

**Comment by alchemyguy** [comment]
`but is there a way to get a live broadcast list without having to do ask permissions and authorization access step?` - no, you'll need user's auth token to access those.
